### ISSUE TITLE
EnvironmentData redefined in RequestList

### ISSUE THREAD

**Issue by jswij** [odwdinc/Python-SimConnect#108]
In https://github.com/odwdinc/Python-SimConnect/blob/6fdae339f752253aa2a45cc2d21b221458c4c459/SimConnect/RequestList.py#L213 the attribute EnvironmentData is defined as an instance of __AircraftEnvironmentData, however in 
In https://github.com/odwdinc/Python-SimConnect/blob/6fdae339f752253aa2a45cc2d21b221458c4c459/SimConnect/RequestList.py#L229
 it is redefined as an instance of __EnvironmentData. This makes the AircraftEnvironmentData unavailable as a group. Of course the data is present in the full list (RequestList.list), however I wanted to have a quick access to groups of data. The various *Data classes provide this, and it is working fine, except for this issue.

**Comment by odwdinc** [comment]
fixed 
https://github.com/odwdinc/Python-SimConnect/commit/50cde9f5e8228f7f2c1eea5037ad0c745de545bd
