### ISSUE TITLE
wrong types for AICreateNonATCAircraft

### ISSUE THREAD

**Issue by fyyyyy** [odwdinc/Python-SimConnect#112]
args 2 + 3 should be c_char_p, not c_double
https://github.com/odwdinc/Python-SimConnect/blob/6fdae339f752253aa2a45cc2d21b221458c4c459/SimConnect/Attributes.py#L585-L586

**Comment by odwdinc** [comment]
fixed

**Comment by fyyyyy** [comment]
thx
