### ISSUE TITLE
Thoughts about the user side

### ISSUE THREAD

**Issue by dooglewoogle** [odwdinc/Python-SimConnect#2]
Hi, I came here from the reddit post, this looks quite promising.

I had a quick go at condensing the user side of the api to the level I reckon is pretty good and kinda feels consistent with other python libraries. At least to me.
Most of the stuff under 'library code' is wrappers, and isn't meant to be how it actually works, just get it kinda going.
The important bit is under 'user code'. 

https://gist.github.com/dooglewoogle/5f06422829b528a699c16766a70b0065

Please let me know what you think.

**Comment by odwdinc** [comment]
Welcome, thank you for your interest, i have attempted to implement your suggestions the best i can, i do want to keep the mapping out side the lib see the new push. 
https://github.com/odwdinc/Python-SimConnect/commit/25c6a94a8bfc5ddc16be03f7c8b352aa8c03daab

**Comment by odwdinc** [comment]
#7 should resolve this feel free to reopen
