### ISSUE TITLE
Removing simconnect.dll

### ISSUE THREAD

**Issue by hankhank10** [odwdinc/Python-SimConnect#23]
Do I understand correctly that the plan before distributing this is to remove simconnect.dll from the repo given it is not open source?

If so, could I understand what the simplest ways are for users to get this file and where they should put the file once they have it (in the python directory?)

I think it would be helpful to add this to the readme

**Comment by odwdinc** [comment]
The release of any code based on the SDK will include a copy of the SimConnect.dll.
I was not 100% but after looking at other projects they all include the SimConnect.dll.
all work on getting it in the PIP release.

**Comment by hankhank10** [comment]
Ok, great - will close this point in that case
