### ISSUE TITLE
User display through browser

### ISSUE THREAD

**Issue by hankhank10** [odwdinc/Python-SimConnect#3]
I am very pleased to have found a python project attempting to work with SimConnect.

What is the end goal of the project?

I would have thought it would be helpful to expose the information pulled out of the sim (and allow control of certain aspects) to the user in a GUI. I would also suggest that the most straightforward way to do this would be through a web based interface so it is platform agnostic.

If this is the plan then I would be very happy to work on the web aspects, which I would propose to run through flask which I am fairly experienced with.

**Comment by odwdinc** [comment]
Hello and thanks for the input, at this time my focuses is on outputting the data and receiving inputs from Arduino like hardware. For GUI I was playing with TK as it seem to be platform agnostic as well. Up for other suggestions so thank you.

My current plan is to use USB based in/out. The use of web services may be help full for wireless sensors and displays. Think ESP32?? raspberry pi?? Not too familiar with flask could it be setup to create a REST bases interface?

**Comment by Heiss** [comment]
Hey,

if you want to use Flask, i would appreciate if you would follow the REST pattern to access any information. For this purpose, it would be very helpful to create an [openapi](http://spec.openapis.org/oas/v3.0.3) (in short OAI) specification, so any developer without python knowledge do not need to take a look into the implementation.  Instead he opens the openapi specification and read it there. There are a lot of tools around OAI (e.g. [online viewer](https://editor.swagger.io/)). The python module [connexion](https://pypi.org/project/connexion/) generates a flask server with the help of such a file. It is very helpful for this purpose. 

With the help of [stoplight studio](https://stoplight.io/studio/) it is very easy to create such openapi specification for a REST API. After this, you only need to link your connexion flask server to this file and you are ready to go: You need to implement multiple methods, which will be resolved through connexion and your openapi file. (More in the connexion doc. It is very simple to use.)

Disclaimer: I am the creator and maintainer of [connexion-plus](https://pypi.org/project/connexion-plus/), which adds some convenience on top of connexion, e.g. easier resolve for multiple resources in one request or monitoring within cluster environments.

**Comment by odwdinc** [comment]
Yah I don't know what i'm doing there with Flask. Totally open for pull request if you want to improve the interface.
I was just trying provide a working sample.

**Comment by hankhank10** [comment]
I have rewritten the flask server and raised a pull request - would appreciate your review.
