### ISSUE TITLE
Data Update Rate

### ISSUE THREAD

**Issue by danricho** [odwdinc/Python-SimConnect#30]
Hi!

First, thanks for your hard work developing this!

I'm having an issue with the data update rate.

- If I poll the data, and log it with a timestamp, say every 250ms, I only get a change in the data every 4 or 5 samples, suggesting that SimConnect's data set is only being refreshed every second.
- I am only using requests.

Is there an issue or am I doing something wrong?

```python
from SimConnect import *
from datetime import datetime
import requests
import time

sm = SimConnect()
aq = AircraftRequests(sm)

while not sm.quit:

    baralt = aq.PositionandSpeedData.get('PLANE_ALTITUDE')
    vs = aq.FlightInstrumentationData.get('VERTICAL_SPEED')
    gs = aq.PositionandSpeedData.get('GROUND_VELOCITY')
    ias = aq.FlightInstrumentationData.get('AIRSPEED_INDICATED')
    lat = aq.PositionandSpeedData.get('PLANE_LATITUDE')
    long = aq.PositionandSpeedData.get('PLANE_LONGITUDE')
    heading = aq.PositionandSpeedData.get('PLANE_HEADING_DEGREES_TRUE') * 57.2958 # rads to degrees

    data = { 
      "ts": datetime.now().strftime('%H:%M:%S.%f')
      "baralt": round(baralt), 
      "vs": round(vs),
      "gs": round(gs),
      "ias": round(ias),
      "lat": lat,
      "long": long,
      "heading":round(heading),
    }

    # the post method is just an example. Have also tested appending the dataset to a list each time, then dumping the list to a JSON file.
    r = requests.post(url = "http://server/api/set/", data = data)
    time.sleep(0.25)

sm.exit()
```

**Comment by odwdinc** [comment]
Hello there,
There is a default time for new data of 2 sec
https://github.com/odwdinc/Python-SimConnect/blob/6522858a2acf0a696ab20018f6ab5cfa4e2818d7/SimConnect/RequestList.py#L28

You should be able to set aq = AircraftRequests(sm, _time=10)
For a 10ms refresh

**Comment by danricho** [comment]
Oh fantastic.

Thanks for your help and sorry to raise it as an issue.

**Comment by odwdinc** [comment]
I miss spoke, the request take that pram
Not AircraftRequests. All fix tomorrow

For now, do a find vs get to get the request object, vs value
See the example.

Then set the time pram for each request
Aka

baralt = aq.find('PLANE_ALTITUDE')

baralt.time=10

To get the value use the value pram,
Aka
baralt.value

Or your normal way should work aswell

**Comment by danricho** [comment]
No worries. I will have a look at it in a few hours.

**Comment by danricho** [comment]
The alternative method with *.value worked well!
Thanks again.

**Comment by odwdinc** [comment]
update is live,
```aq = AircraftRequests(sm, _time=0)``` should now work,
Note, on testing with your data set, I was seeing about 3 refreshes per sec.

**Comment by danricho** [comment]
Sounds good. I’ll try it tonight!

**Comment by danricho** [comment]
@odwdinc 

I have 2 additional questions (not necessarily bugs).

I notice that some signals are set to 57295742.7042 randomly for a single sample. 
Eg: roll might be -14.2432, 57295742.7042, -13.2464
Do you know where this number comes from?

Also, I'm wondering how people determine from the signals whether the simulation is running, loading and paused?

Thanks again!

**Comment by odwdinc** [comment]
I don't know about the 57295742.7042, there is a error number given for data that could not be refresh in the last request.
https://github.com/odwdinc/Python-SimConnect/blob/634b1a7959723b601958ad5476f4558b89e95d72/SimConnect/RequestList.py#L14-L25
Though this is -999999.
Is this the raw data form the request object or are you doing math on it? aka # rads to degrees

for signals, there is just the open and exit handle for now,
```sm.ok``` will be true after open.
this could be expanded to support the others.
https://github.com/odwdinc/Python-SimConnect/blob/634b1a7959723b601958ad5476f4558b89e95d72/SimConnect/SimConnect.py#L75-L77
