### ISSUE TITLE
Event THROTTLE_FULL not working

### ISSUE THREAD

**Issue by AnderGomez14** [odwdinc/Python-SimConnect#32]
I dont know why but when I try to trigger 'THROTTLE_FULL' gives this error

```
event_to_trigger()
TypeError:` 'NoneType' object is not callable
```

I tried with 'THROTTLE_CUT' and it works like it should

**Comment by odwdinc** [comment]
thanks for finding this, seem to be a typo on the auto-gen list there is a space in front,
https://github.com/odwdinc/Python-SimConnect/blob/634b1a7959723b601958ad5476f4558b89e95d72/SimConnect/EventList.py#L95-L97

all fixed in the next push.

**Comment by odwdinc** [comment]
https://github.com/odwdinc/Python-SimConnect/blob/46b4f511fe1134857ee4d067ff453d260fdd62a0/SimConnect/EventList.py#L95-L97
