### ISSUE TITLE
Accessing SimVars that are not listed

### ISSUE THREAD

**Issue by omrygin** [odwdinc/Python-SimConnect#33]
How can one access unlisted SimVars?
I tried manually accessing a LocalVar, but I get `SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED`.
For example, when loading the A320, in DevMode I go to Model Behaviors window (Windows->Model Behaviors), I see a LocalVar named `LANDING_1_Retracted`.

**Comment by odwdinc** [comment]
I'm not 100% what you are asking, the Model Behaviors-> LocalVar, they seem to be local to sim. Aka not exposed via SimConnect. There are other functions of SimConnect that this API dues not map yet. Given that, is this something other SimConnect based projects expose?

Looking at my Windows->Model Behaviors,
 I don't have the LANDING_1_Retracted LocalVar, maybe a bit more of your setup and intent.
There is some interesting info there so may be worth looking into for now it looks as if we don't support it.


If you are trying to just access things like the **LANDING_1_Retracted** info would that not just be the state of
**GEAR POSITION:index**, Note: the Enum seem to be off by one so in code:
```
sm = SimConnect()
aq = AircraftRequests(sm)
gp1 = aq.find("GEAR_POSITION:1")
if gp1.value > 0:
	print("Gear Down")
else:
	print("Gear UP")

```
full list of [aircraft-landing-gear-data](https://docs.microsoft.com/en-us/previous-versions/microsoft-esp/cc526981(v=msdn.10)#aircraft-landing-gear-data)

**Comment by omrygin** [comment]
Sorry for not being more specific.
This is specifically for A320, where the **landing lights bulbs** are retractable.
In the external light panel in the overhead panel of the A320, the left and right landing lights are 3-position switches.
`LANDING_1_Retracted` indicates whether the left landing light bulb is retracted or not.
So you say there is no way to access this boolean?

**Comment by odwdinc** [comment]
Note: SDK seem to be form the 2008, so we may be witting for the updated vision that exposes more sim data

For light data you could try [aircraft-lights-data](https://docs.microsoft.com/en-us/previous-versions/microsoft-esp/cc526981(v=msdn.10)#aircraft-lights-data). There is nothing I can't correlate to what you are asking for though.

If you download the SDK Help->SDK Installer,
check the SDK samples, MSFS SDK\Samples\SimvarWatcher\bin\x64\Release
has a grate program for testing
all supported vars are there.
![image](https://user-images.githubusercontent.com/479214/93671362-2cdcfb80-fa57-11ea-9eb8-e9c580d0ae6b.png)

**Comment by odwdinc** [comment]
I found something ...
you can get the current LANDING_1_Retracted by doing a 
https://github.com/odwdinc/Python-SimConnect/blob/ea93a14b140a0e3c6bbfd61279362b18e48f0b9b/SimConnect/SimConnect.py#L372

The local file will have all the data you want!
I am looking to pars this to expose in API

**Comment by omrygin** [comment]
That's a nice idea!
Will definitely help reading those vars.
I wish there would a way to also set them though without reloading the flight
