### ISSUE TITLE
Speed up connection refresh

### ISSUE THREAD

**Issue by Revel8804** [odwdinc/Python-SimConnect#34]
I would like to do some testing, but i can not seem to figure out how to speed up the connection and refreshes to simconnect.

It looks like the default is 2 sec.

**Comment by hankhank10** [comment]
Do you mean in the web app?

**Comment by odwdinc** [comment]
See the updated [README](https://github.com/odwdinc/Python-SimConnect/blob/master/README.md)
Duplicate of #30
