### ISSUE TITLE
YOKE_X_POSITION and YOKE_Y_POSITION throw error

### ISSUE THREAD

**Issue by AnderGomez14** [odwdinc/Python-SimConnect#35]
Im trying to read the status of the yoke (joystick) by using this code

>     position = aq.get("YOKE_X_POSITION")
>     print(position)

and im getting this error: 

> SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED
> SIMCONNECT_EXCEPTION_UNRECOGNIZED_ID: in (b'YOKE X POSITION', b'Position (-16K to 0) -16K =')
> -999999

**Comment by odwdinc** [comment]
Should be fixed on last push. clean up of autogen code
