### ISSUE TITLE
LoadFlight Function doesn't work

### ISSUE THREAD

**Issue by bchen16** [odwdinc/Python-SimConnect#36]
Hi, I've tried to feed the .flt path to the load_flight() function but it never worked, any idea what I have done wrong? Thanks.

**Comment by odwdinc** [comment]
Did you by chance use absolute path to the .flt?
```
sm = SimConnect()
sm.load_flight("C:\\buld\\Ft2\\FT2.FLT")
sm.exit()
quit()
```
Note: 
As of now you need to be in a flight for load_flight to work, at the "ready to fly screen" is fine.

**Comment by bchen16** [comment]
Oh it works now, thanks!...crashes every time I use it though, haha.  Had to wait for fixes from asobo...

**Comment by odwdinc** [comment]
just for another note:
The save_flight faction works as well, and seem to load ... ok ish ...,

https://github.com/odwdinc/Python-SimConnect/blob/ea93a14b140a0e3c6bbfd61279362b18e48f0b9b/SimConnect/SimConnect.py#L372.

Note form SDK:

Flight | SimConnect_FlightLoad | Partially works | Absolute path for custom flight works correctly. But using the flight from the VFS (same as returned by FlightLoaded) for the main menu gives a simconnect Exception (20: DATA_ERROR), and using its full path raises an Exception in KH side
-- | -- | -- | --

**Comment by bchen16** [comment]
Also loading flight plan works if you don't have a flight plan or have completed a flight plan and shut down. You can submit the ifr to atc, but the flight plan won't show on A320 FMS

**Comment by odwdinc** [comment]
The new function load_flight_plan() shroud work there
Just test with the A320 and the plan loaded and the AI took it fine,
The only place I have found to generate the proper pln file is https://www.simbrief.com/
https://github.com/odwdinc/Python-SimConnect/blob/69b1d3b1500f11a687cb259d427ed6a82134363c/SimConnect/SimConnect.py#L372

**Comment by datavisorbochen** [comment]
I actually have tested this thoroughly. If you load a flight plan after you completed a flight plan, the ai won't recognize it. However if you enter with vfr the ai will take care. And the pln file was generated from simbrief, but it doesn't show on the CDU inside the A320, but the airways shows on the display.
