### ISSUE TITLE
Run python-simconnect on remote machine

### ISSUE THREAD

**Issue by Revel8804** [odwdinc/Python-SimConnect#37]
Is there a way for me to run the python-simconnect on a remote machine? I have seen other programs that are able to use the ip and port 500.

For example i want to run all my python and scripting on 192.168.1.101

My MSFS is running on 192.168.1.102.

so I "should" be able to connect from 192.168.1.101 using   192.168.1.102:500

**Comment by odwdinc** [comment]
What other programs?
more info would be grate

**Comment by Revel8804** [comment]
Right now my initial thought is to run it on a Raspberry Pi.

**Comment by odwdinc** [comment]
Sorry what other programs allow you to use port 500?

**Comment by odwdinc** [comment]
I'm looking to support [SimConnect.cfg ](https://docs.microsoft.com/en-us/previous-versions/microsoft-esp/cc526983(v=msdn.10)#the-simconnectcfg-file)

FYI: this used a dll so Linux is out.
If you are just looking for remote support try the glass_server.

https://github.com/odwdinc/Python-SimConnect/blob/69b1d3b1500f11a687cb259d427ed6a82134363c/glass_server.py#L369
https://github.com/odwdinc/Python-SimConnect/blob/69b1d3b1500f11a687cb259d427ed6a82134363c/glass_server.py#L406
https://github.com/odwdinc/Python-SimConnect/blob/69b1d3b1500f11a687cb259d427ed6a82134363c/glass_server.py#L436

**Comment by Revel8804** [comment]
ahhh good point on the dll.  overlooked that.

thanks for the heads up. I can in theory then just run it as a "server" side component on the MSFS machine and have some thiing else pull the data!
