### ISSUE TITLE
library causes python exit if connect() is called when sim is not running

### ISSUE THREAD

**Issue by gregretkowski** [odwdinc/Python-SimConnect#44]
Thanks for a great library! I've been working on my first project using it - a simple app to control the simrate up/down since that is not displayed in-game. The library is working really well in this application.  When  `connect()` is called and MSFS is not running python exits. It does not print an error nor does it raise an exception. I was hoping to catch exceptions when `connect()` fails but afaict that cannot currently be done. The ask is that connect() raise an catchable exception instead of exiting python.

Steps To Reproduce:

    PS C:\Users\greg\msfstime> python
    Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from SimConnect import SimConnect
    >>> sm = SimConnect(auto_connect=False)
    >>> sm.connect()
    PS C:\Users\greg\msfstime>

**Comment by odwdinc** [comment]
thanks for the pull, merged
