### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by mischeaux** [odwdinc/Python-SimConnect#46]
Hi guys,
don't know an other way to contact the contributors of this than thru an issue, so sorry for that, and please let me know, if I#m totally wrong. But I've some questions about this repo...
First of all, thanks for this wrapper! This is so big for me as I can create my own, desired interface on remote units for the FS2020!

Questions:
1. Is it due to the wrapper or simconnect itself, that the refresh rate is so bad? For controlling switches, it's absolutely ok, but I see no way to let it produce some glass cockpit elements at all. That would be no fun, as can be seen on saasmath's attitude-indicator. Perhaps its due to my hardware (don't think so), but the refresh rate ist really bad for real time applications, I think.
2. Is 1. due to the Python wrapper, or ist it simconnect's "fault"?
3. Is there a way to communicate among the contributors/interrested ones? (E-Mail, Discord, etc.)
4. As I saw some german-like-named contributors. Is this repo german speaking, or english?

Thanks so much and have a nice day!
Michael

**Comment by odwdinc** [comment]
The  data itself is sent and received ~ 0.001 sec, if using:
```aq = AircraftRequests(sm)``` try adding the _time pram:
https://github.com/odwdinc/Python-SimConnect/blob/98df4b44ebd5d7c7e1c304a6d0cf8fb098f6f50d/SimConnect/RequestList.py#L188

```
aq = AircraftRequests(sm, _time=0)
```
[glass_server.py](https://github.com/odwdinc/Python-SimConnect/blob/master/glass_server.py) has a nice sample refreshed at 10ms take a look at the route for test **attitude indicator:**
https://github.com/odwdinc/Python-SimConnect/blob/98df4b44ebd5d7c7e1c304a6d0cf8fb098f6f50d/glass_server.py#L277

1: More info is need, check the closed issue as you are not the first, to ask about the refresh rate.
2: please see https://github.com/odwdinc/Python-SimConnect/issues/33#issuecomment-695312323 for **SimvarWatcher and "is it simconnect's "fault"?"**
3: We all have day jobs and try to get to issue as we can.
4: I'm personally ESL, not bad but not100%, don't mind the typos or miss spellings.

The Documentation is lacking, there is a need to go thought the closed issue and update the documentation. Allwas up for a PR!

**Comment by odwdinc** [comment]
o and welcome and thank for your interest!

**Comment by hankhank10** [comment]
The glass.py is set to refresh every 2 seconds as that is all that was required for my purposes. There's no reason why it shouldn't be able to refresh more often - the only limit will be flask's ability to serve data. You can modify this in the JavaScript. I would be very interested to know how low people can get the refresh rate before it impacts performance.

I am native English speaker.

**Comment by DownInTheShop** [comment]
I'm running some tests for a project I'm doing and just basing it on the Python Interface Example and I need to do more testing but when the _time=200 instead of 2000, I get about 1 out of 9 or 10 responses coming back as "-999999". Is it a timing issue? do I need to drop the altitude.time to 20 from 200?

Also, unrelated to the refresh rate, but what is the difference between aq.find and aq.get?

**Comment by odwdinc** [comment]
@DownInTheShop 
AircraftRequests.find returns
https://github.com/odwdinc/Python-SimConnect/blob/67460bb2987752d4edae65afec7cf4e61d23d56c/SimConnect/RequestList.py#L6
**AircraftRequests.get** and **AircraftRequests.set**, are wrappers to first find and call the get and set of Request object.

I have Added _attemps to AircraftRequests this is by default is set to 4, "-999999" is returned form when the number of attempts are tried, there is a time out of 0.01s between each attempt. By default if we have not received a call back form SimConnect in 0.04s (4*0.01s) then "-999999" is returned. 
Setting _attemps  in AircraftRequests will override all Requests.
```
aq = AircraftRequests(sm, _time=200, _attemps=6)
```
https://github.com/odwdinc/Python-SimConnect/blob/67460bb2987752d4edae65afec7cf4e61d23d56c/SimConnect/RequestList.py#L189

or set the **Request.attemps**
https://github.com/odwdinc/Python-SimConnect/blob/67460bb2987752d4edae65afec7cf4e61d23d56c/SimConnect/RequestList.py#L41

```
aq = AircraftRequests(sm, _time=200)
requestobj = aq .find("something")
requestobj.attemps = 6
```

**Comment by odwdinc** [comment]
@mischeaux did this answer you questions?
