### ISSUE TITLE
Pitch Roll Yaw

### ISSUE THREAD

**Issue by 20chix** [odwdinc/Python-SimConnect#48]
Hi,

Thanks for doing this wrapper. I have a quick question.

Can we extract Pitch Yaw Roll values with this wrapper? I'm not looking to get these values into a web app, just trough a simple script for the moment.

Thanks in advance

**Comment by 20chix** [comment]
I'm assuming these are values I'm looking for 

`"PLANE_PITCH_DEGREES"
"PLANE_BANK_DEGREES"
"PLANE_HEADING_DEGREES_TRUE"`

**Comment by odwdinc** [comment]
yes, see example:
```
from SimConnect import *
sm = SimConnect()
aq = AircraftRequests(sm)
Pitch = aq.find('PLANE_PITCH_DEGREES')  # Pitch Pitch angle, although the name mentions degrees the units used are radians
Yaw  = aq.find('PLANE_HEADING_DEGREES_TRUE')  # Yaw Heading relative to true north, although the name mentions degrees the units used are radians
Roll =  aq.find('PLANE_BANK_DEGREES')  # Roll Bank angle, although the name mentions degrees the units used are radians


print(Pitch.get(), Yaw.get(), Roll.get())

sm.exit()
quit()
```

**Comment by 20chix** [comment]
Hey thanks for this. Just a quick question, what would you recommend for time delay? I would like to get pitch roll and yaw as fast as possible but I noticed that I'm getting lots of 999999999. Any suggestions?

**Comment by odwdinc** [comment]
Try, 
```
aq = AircraftRequests(sm, _time=0, _attemps=10)
```
**_time=0** aka do not cash data this is normally set to 2000 for a 2s cash of data.
**_attemps=10** aka try to get the data 10 times before returning -999999, normal set to 4.
Maybe try tweaking **_attemps** **+** or  **-** ??
