### ISSUE TITLE
Question : FSX support ?

### ISSUE THREAD

**Issue by storca** [odwdinc/Python-SimConnect#49]
Thank you for all the work that has been put in this library.

The question if fairly simple, does this library supports interfacing with FSX:SE ?

If not, will this be a feature or a no-go ? If yes, is it hard to do ?
How could I help ?

**Comment by storca** [comment]
It works indeed with a bit of tweaking!
Not very clean but works fine for me.

The trick is to run the library with python3 **32bit** AND replace the SimConnect.dll by the one located in the FSX:SE folder.

Works for now ^^

**Comment by odwdinc** [comment]
that's cool,
All add some info

**Comment by storca** [comment]
Clarified the procedure in #88
