### ISSUE TITLE
[Request] CHANGELOG.md

### ISSUE THREAD

**Issue by umurkontaci** [odwdinc/Python-SimConnect#50]
Hi, thank you for making this great library.

Given that FS2020 and Python-Simconnect is both moving very fast, it's hard to figure out and discover what's added with a new version.

It would be awesome to have a changelog file that tells us what are new things.

**Comment by odwdinc** [comment]
Take a look at the [**commits**](https://github.com/odwdinc/Python-SimConnect/commits/master)
Trying to keep some sort of description in each one. The best I got for now.
