### ISSUE TITLE
-999999 and sleep length

### ISSUE THREAD

**Issue by mischeaux** [odwdinc/Python-SimConnect#51]
Hi,

just tried to set the sleep length to 0.02, since I've had massive number of -999999 returns.
After that, all values return perfectly.

https://github.com/odwdinc/Python-SimConnect/blob/df70f1d4b077dbf80dd71238e84af6a6a568348b/SimConnect/SimConnect.py#L248

Just saw, that you've updated to a attempt option. But perhaps, the sleep length helps someone ;)

**Comment by odwdinc** [comment]
Thank you for the feedback, will do some more testing on how to handle this.

**Comment by odwdinc** [comment]
I see no change, though I do not see the -999999 as other are reporting. 
Note. all be moving to None vs -999999 for now on.
all update in 0.4.16
