### ISSUE TITLE
Many -999999 when using Python-SimConnect and Godot

### ISSUE THREAD

**Issue by JotaFaD** [odwdinc/Python-SimConnect#53]
Hi everyone, I'm attempting to integrate Python-SimConnect with the Godot game engine using its [python bindings ](https://github.com/touilleMan/godot-python). The purpose is to use Godot as the front end for an application I want to develop. I was able to get it working, but, for some reason, when using godot I get many more -999999 as the result for requests than purely using python.

Here's the code I'm using to workaround the issue. Even with 10 attempts per request, sometimes it takes up to 300 calls before I get a value different from -999999.
```python
from godot import *
from SimConnect import *

sim_connection = SimConnect()
aircraft_events = AircraftEvents(sim_connection)
aircraft_requests = AircraftRequests(sim_connection, _time = 2000, _attemps = 10)

@exposed
class GodotSimConnect(Node2D):
	def _ready(self):
		print('GodotSimConnect loaded')
	
	def get_variable(self, variable):
		result = -999999
		for i in range(1000):
			result = aircraft_requests.get(str(variable))
			if result != -999999:
				print(i)
				return result
		return result
```

This is the script that's calling the function. It's in gdscript (godot's scripting language), but what it does is call `get_variable( )` in the python script with the plane's altitude as the parameter every 2 seconds.
```gdscript
extends Timer

onready var godot_simconnect = get_node("..")

func _ready() -> void:
	connect("timeout", self, "_on_Timer_timeout")
	

func _on_Timer_timeout() -> void:
	print(godot_simconnect.get_variable("PLANE_ALTITUDE"))

```

Using this code, I get a proper value most of the time, but that's because I'm brute forcing it by doing an excessive number of requests, which is far from ideal. Any help would be appreciated.

**Comment by odwdinc** [comment]
I see no problems in the code other than a maybe a misunderstanding.
```
aircraft_requests = AircraftRequests(sim_connection, _time = 2000, _attemps = 10)
```
would try to get new data 10 times every 2s.
If you are intending to get data as fast as posable with out returning cash data maybe try,
```
aircraft_requests = AircraftRequests(sim_connection, _time=0, _attemps=10)
```

Just for testing I set this up to see if the code is returning data or not. 
Note I moved to return **None** vs **-999999** in **0.4.16**
I did not see any output form 
```
if i > 0:
    print(i)
```
Until _attemps got down around 3 or 4. 

```
from SimConnect import *
import logging

logging.basicConfig(level=logging.DEBUG)
LOGGER = logging.getLogger(__name__)
LOGGER.info("START")

# creat simconnection and pass used user classes
sm = SimConnect()
sim_connection = SimConnect()
aircraft_events = AircraftEvents(sim_connection)
aircraft_requests = AircraftRequests(sim_connection, _time=0, _attemps=10)


def test(variable):
	for i in range(1000):
		result = aircraft_requests.get(str(variable))
		if result:
			if i > 0:
				print(i)
			return result
	return result


while True:
	test("PLANE_ALTITUDE")
	test("PLANE_LATITUDE")
	test("PLANE_LONGITUDE")

sm.exit()
quit()
```

**Note.** If you are in any loading screen this will not return valued data. see output of LOGGER for help with knowing game state. This is not fully working in the MSFS2020 sdk.

**Note.** There have been reports of -999999s form more then one user. I'm not seeing them on my side I have pushed a fix another user suggested in **"0.4.16"**
