### ISSUE TITLE
Loading/Saving Flights

### ISSUE THREAD

**Issue by flymypi** [odwdinc/Python-SimConnect#55]
Hello,
first of all hats off to you, this is an amazing project!

I know they aren't documented yet but I have been experimenting with your load_flight() and save_flight() methods.
As I have noticed, flights saved by this method cannot be opened by the sim in its current version.

Upon further investigation, it turns out, that an incomplete [Main] section in the .flt is to blame for that.
Missing the line `MissionType=FreeFlight` will result in the sim not recognizing a flight. When I added it, your flight worked fine.

I don't know if this is new information to you or whether you can even adapt those saving/loading SimConnect functions, but I thought I'd let you know what I found out.

**Comment by odwdinc** [comment]
This is grate info, thank you for testing this out.
right now the best I can think of is something like the https://github.com/odwdinc/Python-SimConnect/blob/668732803c23951a5340b3608be77f2221e0f152/SimConnect/SimConnect.py#L412
as the DLL is the bit writing the file out of the sim.
let me play around a bit and see if I can find something more workable.

**Comment by flymypi** [comment]
> the DLL is the bit writing the file out of the sim.

That's what I suspected. Guess Asobo are still figuring some things out. Until they fix it, I will manipulate the file once more after saving, I guess.

Do you have any insight on why attempting to load via code does either nothing or crash the sim?
Is that also in the hands of the DLL or might it be about encoding, missing right or something that could be fixed?

**Comment by odwdinc** [comment]
hum I'm not having problem loading with load_flight. I do see crashing about every 5th or 6th load.
There is a Note form the SDK. 

Flight | SimConnect_FlightLoad | Partially works | Absolute path for custom flight works correctly. But using the flight from the VFS (same as returned by FlightLoaded) for the main menu gives a simconnect Exception (20: DATA_ERROR), and using its full path raises an Exception in KH side
-- | -- | -- | --

**Comment by odwdinc** [comment]
So after testing for a bit, looks like its a performance problem.
When using the **sm.load_flight**, the sim has to quickly change all of the environment to meet the newly requested environment. I do not see the loading bar. If I pause the game and use the load/save to load the .flt save by **sm.save_flight** the game then will go into a loading screen and the flight loads as expected.
for now I recommend not using **sm.load_flight**.

I have changed **sm.save_flight** to auto append the need fields to the .flt file in **v0.4.17**
all so reworked **sm.dic_to_flight** and **sm.flight_to_dic**

**Comment by flymypi** [comment]
Awesome, thank you very much!
