### ISSUE TITLE
Spaces vs Tabs and other curious questions

### ISSUE THREAD

**Issue by CodeBizarre** [odwdinc/Python-SimConnect#56]
Howdy! I'm working on a PR to fix some spelling/grammar issues and noticed that most of the code is indented using tabs instead of spaces, as this is against the guidelines of [PEP8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces), and general Python practice, I just wanted to know if there is a specific reason for this, or if it would be welcome to convert the files to using spaces while I'm at this?

I'm going to be pretty heavily consuming this library for a project I'm working on, so I plan on contributing more than just some grammar cleanups, and if we're going to be stuck on tabs will need to set up an editor script for that, which is the main reason I'm asking.

**Comment by CodeBizarre** [comment]
As I'm going through the code, I've also just come across lines such as these:
```py
class SIMCONNECT_CLIENT_DATA_SET_FLAG(CtypesEn):  #
    SIMCONNECT_CLIENT_DATA_SET_FLAG_DEFAULT = DWORD(0x00000000)  #
    SIMCONNECT_CLIENT_DATA_SET_FLAG_TAGGED = DWORD(
        0x00000001
    )  # data is in tagged format
```

Is there a purpose of the single hash without a comment at the end of the lines? Want to make sure whatever I do I'm not interfering with something I'm just not familiar with.

**Comment by odwdinc** [comment]
@CodeBizarre started with tabs, will continue per.
"Tabs should be used solely to remain consistent with code that is already indented with tabs."

For the single hash there left over from automated code parsing.
Hope that helps,
