### ISSUE TITLE
Question: sm.map_to_sim_event(b"") vs ae.find("")

### ISSUE THREAD

**Issue by threeGreen** [odwdinc/Python-SimConnect#63]
Hi, first of all thanks to odwdinc for his amazing work and all other contributors as well.
I am not really a programmer and rather new to github.com as well so i don't know where to ask or how to contact odwdinc myself so i like to ask my question here. Sorry if it aint the right place or way to do, we can delete this "issue".

Whats the difference between the following two ways to send an event?
Does it make any difference at all in terms of memory usage, speed or other issues i don't know about?
Which one is preferable?

1.
event_hdg_rot_inc = ae.find("HEADING_BUG_INC")
event_hdg_rot_inc(1)

2.
event_hdg_rot_inc = sm.map_to_sim_event(b"HEADING_BUG_INC")
sm.send_event(event_hdg_rot_inc, 1)

**Comment by odwdinc** [comment]
Welcome and no worriers, you can always ask questions hear.
For 1: The  ae.find() function searches all events for a matching string. aka "HEADING_BUG_INC". Then returns the corresponding constructed Event class object.

For 2: maybe some misunderstanding. sm.send_event() is not to be used directly. As this is called by the event class. https://github.com/odwdinc/Python-SimConnect/blob/b5cf4ef94c5f9d0ddf7db08582dec3dc39383453/SimConnect/EventList.py#L9

**Comment by threeGreen** [comment]
Thank You odwdinc for clarification, so i will continue using  ae.find()
And thanks again for this great library!
