### ISSUE TITLE
get_paused function issue

### ISSUE THREAD

**Issue by danricho** [odwdinc/Python-SimConnect#71]
I have been trying the `sm.get_paused()` function and am receiving the error:

```
...\site-packages\SimConnect\SimConnect.py", line 414, in get_paused
    hr = self.dll.RequestSystemState(
ctypes.ArgumentError: argument 2: <class 'TypeError'>: Don't know how to convert parameter 2
```

Is this function current INOP?

**Comment by MikeNeilson** [comment]
The argtypes array in Attributes.py is empty. If you add the following it will work
`self.RequestSystemState.argtypes = [HANDLE,SIMCONNECT_DATA_REQUEST_ID, c_char_p]`

Should be on line 758: https://github.com/odwdinc/Python-SimConnect/blob/6fdae339f752253aa2a45cc2d21b221458c4c459/SimConnect/Attributes.py#L758

However, what I found is it doesn't actually return a value from the function. In SimConnect.py there's a function that does process the result, but it just prints it to stdout: https://github.com/odwdinc/Python-SimConnect/blob/6fdae339f752253aa2a45cc2d21b221458c4c459/SimConnect/SimConnect.py#L73

I only ran into this same problem this morning so I don't have a solution to the 2nd problem.
