### ISSUE TITLE
License Inconsistencies

### ISSUE THREAD

**Issue by blitzcaster** [odwdinc/Python-SimConnect#76]
License is inconsistent between GitHub repo and PyPi. Which one is currently being enforced?

MIT License (permissive) on PyPi:
https://pypi.org/project/SimConnect/

AGPL 3.0 (strong copyleft) on GitHub:
https://github.com/odwdinc/Python-SimConnect/blob/master/LICENSE

**Comment by odwdinc** [comment]
AGPL 3.0 is the indented License, looks like I forgot to update the meta data on the pip package.

fixed in SimConnect 0.4.23 with: https://github.com/odwdinc/Python-SimConnect/commit/2a6e84cbb24bf4c34b652103c184e03d6dd2d597
