### ISSUE TITLE
Trim?

### ISSUE THREAD

**Issue by EdwardTX2** [odwdinc/Python-SimConnect#81]
Just installed and tried this - awesome! 
any chance of adding slider controls for trim?

**Comment by danricho** [comment]
I think that will be a question for the cockpit companion project:

https://github.com/hankhank10/MSFS2020-cockpit-companion

**Comment by hankhank10** [comment]
My cockpit companion project has now been forked by @mracko into the Cockpit Companion App, which uses the same flask base but takes the functionality much further. https://github.com/mracko/MSFS-Mobile-Companion-App

I don't believe it has trim yet, but it's actively maintained and I'm sure if you raise an issue @mracko would consider adding the functionality.
